// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace aaagenda_contactos.Migrations
{
    [DbContext(typeof(MiDbContext))]
    partial class MiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("agenda", b =>
                {
                    b.Property<int>("ID_agenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_agenda"));

                    b.Property<string>("Descripcion_agenda")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha_agendada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Hora_agendada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre_agenda")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ID_agenda");

                    b.ToTable("Agendas");
                });

            modelBuilder.Entity("contacto", b =>
                {
                    b.Property<int>("ID_contacto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_contacto"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ID_Tipo_Contacto")
                        .HasColumnType("integer");

                    b.Property<int>("ID_Tipo_red_social")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ID_contacto");

                    b.HasIndex("ID_Tipo_Contacto");

                    b.HasIndex("ID_Tipo_red_social");

                    b.ToTable("Contactos");
                });

            modelBuilder.Entity("red_social", b =>
                {
                    b.Property<int>("Id_red_social")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_red_social"));

                    b.Property<int>("ID_contacto")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre_de_usuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id_red_social");

                    b.HasIndex("ID_contacto");

                    b.ToTable("RedesSociales");
                });

            modelBuilder.Entity("teléfono", b =>
                {
                    b.Property<int>("Id_telefono")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_telefono"));

                    b.Property<int>("Id_contacto")
                        .HasColumnType("integer");

                    b.Property<string>("Número_de_teléfono")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Tipo_teléfono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id_telefono");

                    b.HasIndex("Id_contacto");

                    b.ToTable("Telefonos");
                });

            modelBuilder.Entity("tipo_contacto", b =>
                {
                    b.Property<int>("ID_tipo_contacto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_tipo_contacto"));

                    b.Property<string>("Nombre_tipo_contacto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID_tipo_contacto");

                    b.ToTable("TiposContacto");
                });

            modelBuilder.Entity("tipo_red_social", b =>
                {
                    b.Property<int>("Id_tipo_red_social")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_tipo_red_social"));

                    b.Property<string>("Nombre_red_social")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id_tipo_red_social");

                    b.ToTable("TiposRedSocial");
                });

            modelBuilder.Entity("contacto", b =>
                {
                    b.HasOne("tipo_contacto", "TipoContacto")
                        .WithMany()
                        .HasForeignKey("ID_Tipo_Contacto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tipo_red_social", "TipoRedSocial")
                        .WithMany()
                        .HasForeignKey("ID_Tipo_red_social")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoContacto");

                    b.Navigation("TipoRedSocial");
                });

            modelBuilder.Entity("red_social", b =>
                {
                    b.HasOne("contacto", "Contacto")
                        .WithMany()
                        .HasForeignKey("ID_contacto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contacto");
                });

            modelBuilder.Entity("teléfono", b =>
                {
                    b.HasOne("contacto", "Contacto")
                        .WithMany()
                        .HasForeignKey("Id_contacto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contacto");
                });
#pragma warning restore 612, 618
        }
    }
}
